[versions]
agp = "8.13.2"
androidPdfViewer = "3.2.0-beta.1"
appintro = "v5.1.0"
attributionpresenter = "1.0.1"
cardview = "1.0.0"
circleimageview = "3.1.0"
compiler = "5.0.5"
#noinspection GradleDependency
exoplayer = "2.14.2"
glide = "5.0.5"
gson = "2.13.2"
jsoup = "1.21.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
preferenceKtx = "1.2.1"
retrofit = "3.0.0"
swiperefreshlayout = "1.2.0"
volley = "1.2.1"
whatsnew = "0.1.7"

[libraries]
android-pdf-viewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "androidPdfViewer" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
appintro = { module = "com.github.paolorotolo:appintro", version.ref = "appintro" }
attributionpresenter = { module = "com.github.franmontiel:AttributionPresenter", version.ref = "attributionpresenter" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
whatsnew = { module = "io.github.tonnyl:whatsnew", version.ref = "whatsnew" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }